language: java
sudo: false # faster builds

addons:
  sonarcloud:
    organization: sf

script: ./gradlew check sonarqube

deploy:
  provider: script
  script:
    - ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    tags: true