language: java
sudo: false # faster builds
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script:
    - ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    tags: true